services:
  - type: web
    name: calorie-predictor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn calorie_nlp.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 