services:
  - type: web
    name: calorie-predictor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn calorie_nlp.api:app -c gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GUNICORN_CMD_ARGS
        value: "--worker-class uvicorn.workers.UvicornWorker --workers 1 --threads 1"
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
    healthCheckPath: /health
    autoDeploy: true 